"""
This type stub file was generated by pyright.
"""

class TextDetectionMixin:
    def __init__(self, *, limit_side_len=..., limit_type=..., thresh=..., box_thresh=..., unclip_ratio=..., input_shape=..., **kwargs) -> None:
        ...
    


class TextDetectionSubcommandExecutorMixin:
    ...


