"""
This type stub file was generated by pyright.
"""

from ._image_classification import ImageClassification, ImageClassificationSubcommandExecutor

class DocImgOrientationClassification(ImageClassification):
    @property
    def default_model_name(self): # -> Literal['PP-LCNet_x1_0_doc_ori']:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> DocImgOrientationClassificationSubcommandExecutor:
        ...
    


class DocImgOrientationClassificationSubcommandExecutor(ImageClassificationSubcommandExecutor):
    @property
    def subparser_name(self): # -> Literal['doc_img_orientation_classification']:
        ...
    
    @property
    def wrapper_cls(self): # -> type[DocImgOrientationClassification]:
        ...
    


