"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPredictorWrapper, PredictorCLISubcommandExecutor

class DocVLM(PaddleXPredictorWrapper):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def default_model_name(self): # -> Literal['PP-DocBee2-3B']:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> DocVLMSubcommandExecutor:
        ...
    


class DocVLMSubcommandExecutor(PredictorCLISubcommandExecutor):
    input_validator = ...
    @property
    def subparser_name(self): # -> Literal['doc_vlm']:
        ...
    
    def execute_with_args(self, args): # -> None:
        ...
    


