"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPredictorWrapper, PredictorCLISubcommandExecutor

class FormulaRecognition(PaddleXPredictorWrapper):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def default_model_name(self): # -> Literal['PP-FormulaNet_plus-M']:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> FormulaRecognitionSubcommandExecutor:
        ...
    


class FormulaRecognitionSubcommandExecutor(PredictorCLISubcommandExecutor):
    @property
    def subparser_name(self): # -> Literal['formula_recognition']:
        ...
    
    def execute_with_args(self, args): # -> None:
        ...
    


