"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPredictorWrapper, PredictorCLISubcommandExecutor
from ._text_detection import TextDetectionMixin, TextDetectionSubcommandExecutorMixin

class SealTextDetection(TextDetectionMixin, PaddleXPredictorWrapper):
    @property
    def default_model_name(self): # -> Literal['PP-OCRv4_mobile_seal_det']:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> SealTextDetectionSubcommandExecutor:
        ...
    


class SealTextDetectionSubcommandExecutor(TextDetectionSubcommandExecutorMixin, PredictorCLISubcommandExecutor):
    @property
    def subparser_name(self): # -> Literal['seal_text_detection']:
        ...
    
    def execute_with_args(self, args): # -> None:
        ...
    


