"""
This type stub file was generated by pyright.
"""

from ._image_classification import (
    ImageClassification,
    ImageClassificationSubcommandExecutor,
)

class TableClassification(ImageClassification):
    @property
    def default_model_name(self):  # -> Literal['PP-LCNet_x1_0_table_cls']:
        ...
    @classmethod
    def get_cli_subcommand_executor(cls):  # -> TableClassificationSubcommandExecutor:
        ...

class TableClassificationSubcommandExecutor(ImageClassificationSubcommandExecutor):
    @property
    def subparser_name(self):  # -> Literal['table_classification']:
        ...
    @property
    def wrapper_cls(self):  # -> type[TableClassification]:
        ...
