"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPredictorWrapper, PredictorCLISubcommandExecutor

class TableStructureRecognition(PaddleXPredictorWrapper):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def default_model_name(self):  # -> Literal['SLANet']:
        ...
    @classmethod
    def get_cli_subcommand_executor(
        cls,
    ):  # -> TableStructureRecognitionSubcommandExecutor:
        ...

class TableStructureRecognitionSubcommandExecutor(PredictorCLISubcommandExecutor):
    @property
    def subparser_name(self):  # -> Literal['table_structure_recognition']:
        ...
    def execute_with_args(self, args):  # -> None:
        ...
