"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPredictorWrapper, PredictorCLISubcommandExecutor

class TextRecognition(PaddleXPredictorWrapper):
    def __init__(self, *, input_shape=..., **kwargs) -> None: ...
    @property
    def default_model_name(self):  # -> Literal['PP-OCRv5_server_rec']:
        ...
    @classmethod
    def get_cli_subcommand_executor(cls):  # -> TextRecognitionSubcommandExecutor:
        ...

class TextRecognitionSubcommandExecutor(PredictorCLISubcommandExecutor):
    @property
    def subparser_name(self):  # -> Literal['text_recognition']:
        ...
    def execute_with_args(self, args):  # -> None:
        ...
