"""
This type stub file was generated by pyright.
"""

from ._image_classification import ImageClassification, ImageClassificationSubcommandExecutor

class TextLineOrientationClassification(ImageClassification):
    @property
    def default_model_name(self): # -> Literal['PP-LCNet_x0_25_textline_ori']:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> TextLineOrientationClassificationSubcommandExecutor:
        ...
    


class TextLineOrientationClassificationSubcommandExecutor(ImageClassificationSubcommandExecutor):
    @property
    def subparser_name(self): # -> Literal['textline_orientation_classification']:
        ...
    
    @property
    def wrapper_cls(self): # -> type[TextLineOrientationClassification]:
        ...
    


