"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPredictorWrapper, PredictorCLISubcommandExecutor

class TextImageUnwarping(PaddleXPredictorWrapper):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def default_model_name(self): # -> Literal['UVDoc']:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> TextImageUnwarpingSubcommandExecutor:
        ...
    


class TextImageUnwarpingSubcommandExecutor(PredictorCLISubcommandExecutor):
    @property
    def subparser_name(self): # -> Literal['text_image_unwarping']:
        ...
    
    def execute_with_args(self, args): # -> None:
        ...
    


