"""
This type stub file was generated by pyright.
"""

_activeEngines = ...

def init(driverName=..., debug=...):  # -> Engine:
    """
    Constructs a new TTS engine instance or reuses the existing instance for
    the driver name.

    @param driverName: Name of the platform specific driver to use. If
        None, selects the default driver for the operating system.
    @type: str
    @param debug: Debugging output enabled or not
    @type debug: bool
    @return: Engine instance
    @rtype: L{engine.Engine}
    """
    ...

def speak(text) -> None: ...
