"""
This type stub file was generated by pyright.
"""

_engines_by_sys_platform = ...
def engines_by_sys_platform() -> tuple[str]:
    """
    Return the names of all TTS engines for the current operating system.
    If sys.platform is not in _engines_by_sys_platform, return ("espeak",).
    """
    ...

def default_engine_by_sys_platform() -> str:
    """
    Return the name of the default TTS engine for the current operating system.
    The first engine in the value tuple is the default engine for that platform.
    """
    ...

class Engine:
    """
    @ivar proxy: Proxy to a driver implementation
    @type proxy: L{DriverProxy}
    @ivar _connects: Array of subscriptions
    @type _connects: list
    @ivar _inLoop: Running an event loop or not
    @type _inLoop: bool
    @ivar _driverLoop: Using a driver event loop or not
    @type _driverLoop: bool
    @ivar _debug: Print exceptions or not
    @type _debug: bool.
    """
    def __init__(self, driverName: str | None = ..., debug: bool = ...) -> None:
        """
        Constructs a new TTS engine instance.

        @param driverName: Name of the platform specific driver to use. If
            None, selects the default driver for the operating system.
        @type: str
        @param debug: Debugging output enabled or not
        @type debug: bool
        """
        ...
    
    def __repr__(self) -> str:
        """repr(pyttsx3.init('nsss')) -> "pyttsx3.engine.Engine('nsss', debug=False)"."""
        ...
    
    def __str__(self) -> str:
        """str(pyttsx3.init('nsss')) -> 'nsss'."""
        ...
    
    def connect(self, topic: str, cb: callable) -> dict:
        """
        Registers a callback for an event topic. Valid topics and their
        associated values:

        started-utterance: name=<str>
        started-word: name=<str>, location=<int>, length=<int>
        finished-utterance: name=<str>, completed=<bool>
        error: name=<str>, exception=<exception>

        @param topic: Event topic name
        @type topic: str
        @param cb: Callback function
        @type cb: callable
        @return: Token to use to unregister
        @rtype: dict
        """
        ...
    
    def disconnect(self, token: dict) -> None:
        """
        Unregisters a callback for an event topic.

        @param token: Token of the callback to unregister
        @type token: dict
        """
        ...
    
    def say(self, text: str | None, name: str | None = ...) -> str | None:
        """
        Adds an utterance to speak to the event queue.

        @param text: Text to speak
        @type text: unicode
        @param name: Name to associate with this utterance. Included in
            notifications about this utterance.
        @type name: str
        """
        ...
    
    def stop(self) -> None:
        """Stops the current utterance and clears the event queue."""
        ...
    
    def save_to_file(self, text: str, filename: str, name: str | None = ...) -> None:
        """
        Adds an utterance to speak to the event queue.

        @param text: Text to speak
        @type text: unicode
        @param filename: the name of file to save.
        @param name: Name to associate with this utterance. Included in
            notifications about this utterance.
        @type name: str
        """
        ...
    
    def isBusy(self) -> bool:
        """
        @return: True if an utterance is currently being spoken, false if not
        @rtype: bool.
        """
        ...
    
    def getProperty(self, name: str) -> object:
        """
        Gets the current value of a property. Valid names and values include:

        voices: List of L{voice.Voice} objects supported by the driver
        voice: String ID of the current voice
        rate: Integer speech rate in words per minute
        volume: Floating point volume of speech in the range [0.0, 1.0]

        Numeric values outside the valid range supported by the driver are
        clipped.

        @param name: Name of the property to fetch
        @type name: str
        @return: Value associated with the property
        @rtype: object
        @raise KeyError: When the property name is unknown
        """
        ...
    
    def setProperty(self, name: str, value: str | float) -> None:
        """
        Adds a property value to set to the event queue. Valid names and values
        include:

        voice: String ID of the voice
        rate: Integer speech rate in words per minute
        volume: Floating point volume of speech in the range [0.0, 1.0]

        Numeric values outside the valid range supported by the driver are
        clipped.

        @param name: Name of the property to fetch
        @type name: str
        @param: Value to set for the property
        @rtype: object
        @raise KeyError: When the property name is unknown
        """
        ...
    
    def runAndWait(self) -> None:
        """
        Runs an event loop until all commands queued up until this method call
        complete. Blocks during the event loop and returns when the queue is
        cleared.

        @raise RuntimeError: When the loop is already running
        """
        ...
    
    def startLoop(self, useDriverLoop: bool = ...) -> None:
        """
        Starts an event loop to process queued commands and callbacks.

        @param useDriverLoop: If True, uses the run loop provided by the driver
            (the default). If False, assumes the caller will enter its own
            run loop which will pump any events for the TTS engine properly.
        @type useDriverLoop: bool
        @raise RuntimeError: When the loop is already running
        """
        ...
    
    def endLoop(self) -> None:
        """
        Stops a running event loop.

        @raise RuntimeError: When the loop is not running
        """
        ...
    
    def iterate(self) -> None:
        """Must be called regularly when using an external event loop."""
        ...
    


