"""
This type stub file was generated by pyright.
"""

class Voice:
    def __init__(self, id, name=..., languages=..., gender=..., age=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


