"""
This type stub file was generated by pyright.
"""

def str2bool(v, /): # -> bool:
    ...

def get_subcommand_args(args):
    ...

def add_simple_inference_args(subparser, *, input_help=...): # -> None:
    ...

def perform_simple_inference(wrapper_cls, params, predict_param_names=...): # -> None:
    ...

