"""
This type stub file was generated by pyright.
"""

import argparse

class CLIDeprecationWarning(DeprecationWarning): ...

class DeprecatedOptionAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=...):  # -> None:
        ...

def warn_deprecated_param(name, new_name=...):  # -> None:
    ...
