"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPipelineWrapper, PipelineCLISubcommandExecutor

class DocPreprocessor(PaddleXPipelineWrapper):
    def __init__(self, doc_orientation_classify_model_name=..., doc_orientation_classify_model_dir=..., doc_unwarping_model_name=..., doc_unwarping_model_dir=..., use_doc_orientation_classify=..., use_doc_unwarping=..., **kwargs) -> None:
        ...
    
    def predict_iter(self, input, *, use_doc_orientation_classify=..., use_doc_unwarping=...):
        ...
    
    def predict(self, input, *, use_doc_orientation_classify=..., use_doc_unwarping=...): # -> list[Any]:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> DocPreprocessorCLISubcommandExecutor:
        ...
    


class DocPreprocessorCLISubcommandExecutor(PipelineCLISubcommandExecutor):
    @property
    def subparser_name(self): # -> Literal['doc_preprocessor']:
        ...
    
    def execute_with_args(self, args): # -> None:
        ...
    


