"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPipelineWrapper, PipelineCLISubcommandExecutor

class DocUnderstanding(PaddleXPipelineWrapper):
    def __init__(self, doc_understanding_model_name=..., doc_understanding_model_dir=..., doc_understanding_batch_size=..., **kwargs) -> None:
        ...
    
    def predict_iter(self, input, **kwargs):
        ...
    
    def predict(self, input, **kwargs): # -> list[Any]:
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> DocUnderstandingCLISubcommandExecutor:
        ...
    


class DocUnderstandingCLISubcommandExecutor(PipelineCLISubcommandExecutor):
    input_validator = ...
    @property
    def subparser_name(self): # -> Literal['doc_understanding']:
        ...
    
    def execute_with_args(self, args): # -> None:
        ...
    


