"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPipelineWrapper, PipelineCLISubcommandExecutor

class FormulaRecognitionPipeline(PaddleXPipelineWrapper):
    def __init__(
        self,
        doc_orientation_classify_model_name=...,
        doc_orientation_classify_model_dir=...,
        doc_orientation_classify_batch_size=...,
        doc_unwarping_model_name=...,
        doc_unwarping_model_dir=...,
        doc_unwarping_batch_size=...,
        use_doc_orientation_classify=...,
        use_doc_unwarping=...,
        layout_detection_model_name=...,
        layout_detection_model_dir=...,
        layout_threshold=...,
        layout_nms=...,
        layout_unclip_ratio=...,
        layout_merge_bboxes_mode=...,
        layout_detection_batch_size=...,
        use_layout_detection=...,
        formula_recognition_model_name=...,
        formula_recognition_model_dir=...,
        formula_recognition_batch_size=...,
        **kwargs,
    ) -> None: ...
    def predict_iter(
        self,
        input,
        *,
        use_layout_detection=...,
        use_doc_orientation_classify=...,
        use_doc_unwarping=...,
        layout_det_res=...,
        layout_threshold=...,
        layout_nms=...,
        layout_unclip_ratio=...,
        layout_merge_bboxes_mode=...,
        **kwargs,
    ): ...
    def predict(
        self,
        input,
        *,
        use_layout_detection=...,
        use_doc_orientation_classify=...,
        use_doc_unwarping=...,
        layout_det_res=...,
        layout_threshold=...,
        layout_nms=...,
        layout_unclip_ratio=...,
        layout_merge_bboxes_mode=...,
        **kwargs,
    ):  # -> list[Any]:
        ...
    @classmethod
    def get_cli_subcommand_executor(
        cls,
    ):  # -> FormulaRecognitionPipelineCLISubcommandExecutor:
        ...

class FormulaRecognitionPipelineCLISubcommandExecutor(PipelineCLISubcommandExecutor):
    @property
    def subparser_name(self):  # -> Literal['formula_recognition_pipeline']:
        ...
    def execute_with_args(self, args):  # -> None:
        ...
