"""
This type stub file was generated by pyright.
"""

from .base import PaddleXPipelineWrapper, PipelineCLISubcommandExecutor

class PPChatOCRv4Doc(PaddleXPipelineWrapper):
    def __init__(self, layout_detection_model_name=..., layout_detection_model_dir=..., doc_orientation_classify_model_name=..., doc_orientation_classify_model_dir=..., doc_unwarping_model_name=..., doc_unwarping_model_dir=..., text_detection_model_name=..., text_detection_model_dir=..., textline_orientation_model_name=..., textline_orientation_model_dir=..., textline_orientation_batch_size=..., text_recognition_model_name=..., text_recognition_model_dir=..., text_recognition_batch_size=..., table_structure_recognition_model_name=..., table_structure_recognition_model_dir=..., seal_text_detection_model_name=..., seal_text_detection_model_dir=..., seal_text_recognition_model_name=..., seal_text_recognition_model_dir=..., seal_text_recognition_batch_size=..., use_doc_orientation_classify=..., use_doc_unwarping=..., use_textline_orientation=..., use_seal_recognition=..., use_table_recognition=..., layout_threshold=..., layout_nms=..., layout_unclip_ratio=..., layout_merge_bboxes_mode=..., text_det_limit_side_len=..., text_det_limit_type=..., text_det_thresh=..., text_det_box_thresh=..., text_det_unclip_ratio=..., text_rec_score_thresh=..., seal_det_limit_side_len=..., seal_det_limit_type=..., seal_det_thresh=..., seal_det_box_thresh=..., seal_det_unclip_ratio=..., seal_rec_score_thresh=..., retriever_config=..., mllm_chat_bot_config=..., chat_bot_config=..., **kwargs) -> None:
        ...
    
    def save_vector(self, vector_info, save_path, retriever_config=...):
        ...
    
    def load_vector(self, data_path, retriever_config=...):
        ...
    
    def load_visual_info_list(self, data_path):
        ...
    
    def save_visual_info_list(self, visual_info, save_path):
        ...
    
    def visual_predict_iter(self, input, *, use_doc_orientation_classify=..., use_doc_unwarping=..., use_textline_orientation=..., use_seal_recognition=..., use_table_recognition=..., layout_threshold=..., layout_nms=..., layout_unclip_ratio=..., layout_merge_bboxes_mode=..., text_det_limit_side_len=..., text_det_limit_type=..., text_det_thresh=..., text_det_box_thresh=..., text_det_unclip_ratio=..., text_rec_score_thresh=..., seal_det_limit_side_len=..., seal_det_limit_type=..., seal_det_thresh=..., seal_det_box_thresh=..., seal_det_unclip_ratio=..., seal_rec_score_thresh=..., **kwargs):
        ...
    
    def visual_predict(self, input, *, use_doc_orientation_classify=..., use_doc_unwarping=..., use_textline_orientation=..., use_seal_recognition=..., use_table_recognition=..., layout_threshold=..., layout_nms=..., layout_unclip_ratio=..., layout_merge_bboxes_mode=..., text_det_limit_side_len=..., text_det_limit_type=..., text_det_thresh=..., text_det_box_thresh=..., text_det_unclip_ratio=..., text_rec_score_thresh=..., seal_det_limit_side_len=..., seal_det_limit_type=..., seal_det_thresh=..., seal_det_box_thresh=..., seal_det_unclip_ratio=..., seal_rec_score_thresh=..., **kwargs): # -> list[Any]:
        ...
    
    def build_vector(self, visual_info, *, min_characters=..., block_size=..., flag_save_bytes_vector=..., retriever_config=...):
        ...
    
    def mllm_pred(self, input, key_list, *, mllm_chat_bot_config=...):
        ...
    
    def chat(self, key_list, visual_info, *, use_vector_retrieval=..., vector_info=..., min_characters=..., text_task_description=..., text_output_format=..., text_rules_str=..., text_few_shot_demo_text_content=..., text_few_shot_demo_key_value_list=..., table_task_description=..., table_output_format=..., table_rules_str=..., table_few_shot_demo_text_content=..., table_few_shot_demo_key_value_list=..., mllm_predict_info=..., mllm_integration_strategy=..., chat_bot_config=..., retriever_config=...):
        ...
    
    @classmethod
    def get_cli_subcommand_executor(cls): # -> PPChatOCRv4DocCLISubcommandExecutor:
        ...
    


class PPChatOCRv4DocCLISubcommandExecutor(PipelineCLISubcommandExecutor):
    @property
    def subparser_name(self): # -> Literal['pp_chatocrv4_doc']:
        ...
    
    def execute_with_args(self, args): # -> None:
        ...
    


