"""
This type stub file was generated by pyright.
"""

import abc

class CLISubcommandExecutor(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def add_subparser(self, subparsers):
        ...
    
    @abc.abstractmethod
    def execute_with_args(self, args):
        ...
    


