"""
This type stub file was generated by pyright.
"""

def parse_common_args(kwargs, *, default_enable_hpi):  # -> dict[Any, Any]:
    ...
def prepare_common_init_args(model_name, common_args):  # -> dict[Any, Any]:
    ...
def add_common_cli_opts(
    parser, *, default_enable_hpi, allow_multiple_devices
):  # -> None:
    ...
